version: "3.8"

services:
  db:
    image: arangodb
    volumes:
      - ./database/data:/var/lib/arangodb3
      - ./database/apps:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=test
    ports:
      - "8529:8529"